name: Build Kube-Proxy images

on:
  push:
    branches: [master]
    paths:
      - 'hostprocess/calico/kube-proxy/**'
      - '.github/workflows/build-kube-proxy-images.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: docker login ghcr
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: docker build & push
        working-directory: hostprocess/calico/kube-proxy
        run: |
          docker build --build-arg k8sVersion=v1.34.6 -t ghcr.io/appmana/kube-proxy:v1.34.6-calico-hostprocess .
          docker push ghcr.io/appmana/kube-proxy:v1.34.6-calico-hostprocess
